import Head from "next/head";
import Sidebar from "../components/Sidebar";

function chat() {
  return (
    <>
      <Head>
        <title>Whatsapp with Chimpaji</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div></div>
    </>
  );
}

export default chat;
